stages:
  - test
  - deploy

test:
  stage: test
  image: theopenstore/ci
  before_script:
    - npm install
  script:
    - npm run translations
    - npm run generate-icons
    - npm run lint

deploy:
  stage: deploy
  only:
    - master
  image: theopenstore/ci
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - npm install
  script:
    - VERSION=$(date +"%Y-%m-%d_%H-%M-%S")
    - echo $VERSION
    - npm run translations
    - npm run generate-icons
    - rsync -av --delete --exclude node_modules --exclude ".git" . root@ssh.open-store.io:/srv/openstore-web/$VERSION
    - ssh root@ssh.open-store.io "/srv/openstore-web/$VERSION/deploy/post-deploy.sh $VERSION"

deploy_staging:
  stage: deploy
  only:
    - staging
  image: theopenstore/ci
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - npm install
  script:
    - ENV=-staging
    - VERSION=$(date +"%Y-%m-%d_%H-%M-%S")
    - echo $VERSION
    - npm run translations
    - npm run generate-icons
    - rsync -av --delete --exclude node_modules --exclude ".git" . root@ssh.open-store.io:/srv/openstore-web$ENV/$VERSION
    - ssh root@ssh.open-store.io "/srv/openstore-web$ENV/$VERSION/deploy/post-deploy.sh $VERSION $ENV"

sast:
  variables:
    SAST_EXCLUDED_PATHS: spec, test, tests, tmp, po, deploy
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, eslint, flawfinder, gosec, kubesec,
      phpcs-security-audit, pmd-apex, security-code-scan, sobelow, spotbugs
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
